
import Head from 'next/head'
import router from 'next/router';
import { useState } from 'react';
import { useRoom } from '../contexts/room';


export default function Home() {

  // const [roomId, setRoomId] = useState<string>("cl9zpex2j0000lpoi1kjiqr6f")
  // const [memberId, setMemberId] = useState<string>("cl9zpex3o0013lpoi18mwu9d7")

  const { roomId, updateRoomId, memberId, updateMemberId } = useRoom();

  return (
    <div className="w-screen h-screen">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-full w-full  flex flex-col items-center  pt-[10%] bg-[#070707]'>
        <div className='border-slate-500 text-black w-1/2 p-10 rounded-lg'>
          <p className='w-full flex justify-center text-white mb-4 text-2xl font-medium'>
            Join Room
          </p>
          <div className='w-full flex flex-col gap-y-5 justify-center'>
            <label className="block text-white font-light mb-1 text-xl " >
              Room Id
            </label>
            <input
              value={roomId}
              onChange={(e) => {
                updateRoomId(e.target.value)
              }}
              className="shadow appearance-none text-white bg-transparent border-t-0 border-l-0 border-r-0 border w-full pb-2   leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Room Id" />
            <label className="block text-white font-light  text-xl ">
              Member Id
            </label>
            <input
              value={memberId}
              onChange={(e) => {
                updateMemberId(e.target.value)
              }}
              className="shadow appearance-none text-white bg-transparent border-t-0 border-l-0 border-r-0 border w-full pb-2  leading-tight focus:outline-none focus:shadow-outline bg" id="username" type="text" placeholder="Member Id" />
          </div>
        </div>
        <button
          className='bg-orange-400 p-2 px-6 text-white rounded-md w-[30%]'
          onClick={async () => {
            if (roomId != null && memberId != null)
              router.push("/room")
          }}>
          Join Room
        </button>
      </main >

    </div >
  )
}
